export const CAT_COLORS = {
  Streamer: "#FF00AA",
  Creator: "#00F5FF",
  Rapper: "#7B2CFF",
  Pop: "#ff5ce1",
  Athlete: "#ffd76a",
  Brand: "#8ee0ff",
  Game: "#c084fc",
  Community: "#00e5a0",
  Meme: "#9aa0b8",
  Anime: "#ff7ab6",
  KPop: "#ff9ff3",
  TikTok: "#69f0ae",
  Influencer: "#ffb347",
};

export const PERSONALITIES = [
  // Streamers & creators
  {
    id: "kai",
    name: "Kai Cenat",
    handle: "@kai",
    cat: "Streamer",
    emoji: "🎙️",
    aura: 4820,
    rizz: 98,
    drip: 90,
    mce: 96,
    wl: 95,
  },
  {
    id: "mrbeast",
    name: "MrBeast",
    handle: "@mrbeast",
    cat: "Creator",
    emoji: "🤑",
    aura: 4710,
    rizz: 70,
    drip: 74,
    mce: 82,
    wl: 99,
  },
  {
    id: "speed",
    name: "IShowSpeed",
    handle: "@speed",
    cat: "Streamer",
    emoji: "⚡",
    aura: 3890,
    rizz: 84,
    drip: 60,
    mce: 94,
    wl: 78,
  },
  {
    id: "caseoh",
    name: "CaseOh",
    handle: "@caseoh",
    cat: "Streamer",
    emoji: "🍔",
    aura: 3640,
    rizz: 72,
    drip: 66,
    mce: 88,
    wl: 90,
  },
  {
    id: "xqc",
    name: "xQc",
    handle: "@xqc",
    cat: "Streamer",
    emoji: "🟣",
    aura: 2870,
    rizz: 62,
    drip: 55,
    mce: 70,
    wl: 65,
  },
  {
    id: "pokimane",
    name: "Pokimane",
    handle: "@pokimane",
    cat: "Streamer",
    emoji: "🍑",
    aura: 2650,
    rizz: 74,
    drip: 78,
    mce: 71,
    wl: 82,
  },
  {
    id: "valkyrae",
    name: "Valkyrae",
    handle: "@valkyrae",
    cat: "Streamer",
    emoji: "🎧",
    aura: 2380,
    rizz: 76,
    drip: 81,
    mce: 73,
    wl: 84,
  },
  {
    id: "hasanabi",
    name: "HasanAbi",
    handle: "@hasanabi",
    cat: "Streamer",
    emoji: "📰",
    aura: 1960,
    rizz: 66,
    drip: 58,
    mce: 72,
    wl: 76,
  },
  // Music
  {
    id: "taylor",
    name: "Taylor Swift",
    handle: "@taylorswift",
    cat: "Pop",
    emoji: "🎤",
    aura: 3560,
    rizz: 88,
    drip: 92,
    mce: 85,
    wl: 97,
  },
  {
    id: "drake",
    name: "Drake",
    handle: "@drake",
    cat: "Rapper",
    emoji: "🦉",
    aura: 3420,
    rizz: 85,
    drip: 90,
    mce: 74,
    wl: 88,
  },
  {
    id: "kdot",
    name: "Kendrick Lamar",
    handle: "@kdot",
    cat: "Rapper",
    emoji: "🐐",
    aura: 3310,
    rizz: 91,
    drip: 88,
    mce: 93,
    wl: 96,
  },
  {
    id: "travis",
    name: "Travis Scott",
    handle: "@travisscott",
    cat: "Rapper",
    emoji: "🌵",
    aura: 2540,
    rizz: 76,
    drip: 95,
    mce: 84,
    wl: 80,
  },
  {
    id: "badbunny",
    name: "Bad Bunny",
    handle: "@badbunny",
    cat: "Rapper",
    emoji: "🐰",
    aura: 2290,
    rizz: 92,
    drip: 89,
    mce: 87,
    wl: 90,
  },
  {
    id: "sabrina",
    name: "Sabrina Carpenter",
    handle: "@sabrina",
    cat: "Pop",
    emoji: "🍒",
    aura: 2430,
    rizz: 90,
    drip: 93,
    mce: 86,
    wl: 91,
  },
  {
    id: "billie",
    name: "Billie Eilish",
    handle: "@billie",
    cat: "Pop",
    emoji: "🖤",
    aura: 2060,
    rizz: 79,
    drip: 85,
    mce: 80,
    wl: 89,
  },
  {
    id: "arianagrande",
    name: "Ariana Grande",
    handle: "@arianagrande",
    cat: "Pop",
    emoji: "🎀",
    aura: 2410,
    rizz: 80,
    drip: 84,
    mce: 77,
    wl: 88,
  },
  {
    id: "theweeknd",
    name: "The Weeknd",
    handle: "@theweeknd",
    cat: "Pop",
    emoji: "🌑",
    aura: 2350,
    rizz: 81,
    drip: 89,
    mce: 79,
    wl: 86,
  },
  // K-Pop
  {
    id: "bts",
    name: "BTS",
    handle: "@bts",
    cat: "KPop",
    emoji: "💜",
    aura: 2990,
    rizz: 82,
    drip: 88,
    mce: 84,
    wl: 95,
  },
  {
    id: "blackpink",
    name: "BLACKPINK",
    handle: "@blackpink",
    cat: "KPop",
    emoji: "🩷",
    aura: 2710,
    rizz: 85,
    drip: 90,
    mce: 83,
    wl: 92,
  },
  // TikTok
  {
    id: "charlidamelio",
    name: "Charli D'Amelio",
    handle: "@charlidamelio",
    cat: "TikTok",
    emoji: "💃",
    aura: 2240,
    rizz: 71,
    drip: 80,
    mce: 68,
    wl: 79,
  },
  // Anime
  {
    id: "gojo",
    name: "Gojo Satoru",
    handle: "@gojosatoru",
    cat: "Anime",
    emoji: "🔮",
    aura: 3520,
    rizz: 93,
    drip: 94,
    mce: 95,
    wl: 91,
  },
  {
    id: "goku",
    name: "Goku",
    handle: "@son_goku",
    cat: "Anime",
    emoji: "🧡",
    aura: 3400,
    rizz: 74,
    drip: 60,
    mce: 97,
    wl: 94,
  },
  {
    id: "luffy",
    name: "Luffy",
    handle: "@strawhat",
    cat: "Anime",
    emoji: "👒",
    aura: 3160,
    rizz: 79,
    drip: 68,
    mce: 96,
    wl: 90,
  },
  {
    id: "naruto",
    name: "Naruto",
    handle: "@hokage",
    cat: "Anime",
    emoji: "🍥",
    aura: 2880,
    rizz: 77,
    drip: 63,
    mce: 93,
    wl: 86,
  },
  // Sports
  {
    id: "lebron",
    name: "LeBron James",
    handle: "@kingjames",
    cat: "Athlete",
    emoji: "👑",
    aura: 3180,
    rizz: 80,
    drip: 82,
    mce: 90,
    wl: 94,
  },
  {
    id: "ronaldo",
    name: "Cristiano Ronaldo",
    handle: "@cristiano",
    cat: "Athlete",
    emoji: "⚽",
    aura: 3050,
    rizz: 95,
    drip: 94,
    mce: 92,
    wl: 93,
  },
  {
    id: "messi",
    name: "Lionel Messi",
    handle: "@leomessi",
    cat: "Athlete",
    emoji: "🥇",
    aura: 3120,
    rizz: 78,
    drip: 76,
    mce: 79,
    wl: 98,
  },
  {
    id: "curry",
    name: "Stephen Curry",
    handle: "@stephencurry",
    cat: "Athlete",
    emoji: "🏀",
    aura: 2995,
    rizz: 77,
    drip: 79,
    mce: 82,
    wl: 96,
  },
  {
    id: "ohtani",
    name: "Shohei Ohtani",
    handle: "@shoheiohtani",
    cat: "Athlete",
    emoji: "⚾",
    aura: 2620,
    rizz: 69,
    drip: 72,
    mce: 80,
    wl: 97,
  },
  {
    id: "clark",
    name: "Caitlin Clark",
    handle: "@caitlinclark",
    cat: "Athlete",
    emoji: "🌟",
    aura: 2330,
    rizz: 68,
    drip: 71,
    mce: 78,
    wl: 93,
  },
  // Games
  {
    id: "gta6",
    name: "GTA VI",
    handle: "@gta6",
    cat: "Game",
    emoji: "🎮",
    aura: 2660,
    rizz: 58,
    drip: 86,
    mce: 91,
    wl: 99,
  },
  {
    id: "fortnite",
    name: "Fortnite",
    handle: "@fortnite",
    cat: "Game",
    emoji: "🛡️",
    aura: 2180,
    rizz: 61,
    drip: 70,
    mce: 75,
    wl: 92,
  },
  {
    id: "minecraft",
    name: "Minecraft",
    handle: "@minecraft",
    cat: "Game",
    emoji: "⛏️",
    aura: 2450,
    rizz: 60,
    drip: 55,
    mce: 74,
    wl: 95,
  },
  {
    id: "valorant",
    name: "Valorant",
    handle: "@valorant",
    cat: "Game",
    emoji: "🎯",
    aura: 2270,
    rizz: 63,
    drip: 66,
    mce: 72,
    wl: 88,
  },
  // Brands
  {
    id: "elon",
    name: "Elon Musk",
    handle: "@elonmusk",
    cat: "Brand",
    emoji: "🚀",
    aura: 2310,
    rizz: 55,
    drip: 61,
    mce: 66,
    wl: 71,
  },
  {
    id: "netflix",
    name: "Netflix",
    handle: "@netflix",
    cat: "Brand",
    emoji: "🍿",
    aura: 2940,
    rizz: 62,
    drip: 70,
    mce: 76,
    wl: 91,
  },
  {
    id: "nike",
    name: "Nike",
    handle: "@nike",
    cat: "Brand",
    emoji: "✅",
    aura: 2680,
    rizz: 63,
    drip: 91,
    mce: 77,
    wl: 90,
  },
  // Influencers
  {
    id: "kimkardashian",
    name: "Kim Kardashian",
    handle: "@kimkardashian",
    cat: "Influencer",
    emoji: "📸",
    aura: 2760,
    rizz: 64,
    drip: 82,
    mce: 69,
    wl: 70,
  },
  // Community
  {
    id: "groupchat",
    name: "The Group Chat",
    handle: "@groupchat",
    cat: "Community",
    emoji: "💬",
    aura: 1950,
    rizz: 68,
    drip: 64,
    mce: 78,
    wl: 85,
  },
  // Memes
  {
    id: "therock",
    name: "The Rock",
    handle: "@therock",
    cat: "Meme",
    emoji: "🗿",
    aura: 2520,
    rizz: 66,
    drip: 68,
    mce: 88,
    wl: 90,
  },
  {
    id: "yourex",
    name: "Your Ex",
    handle: "@yourexc",
    cat: "Meme",
    emoji: "💀",
    aura: 1720,
    rizz: 40,
    drip: 45,
    mce: 38,
    wl: 12,
  },
  {
    id: "skibidi",
    name: "Skibidi Toilet",
    handle: "@skibidi",
    cat: "Meme",
    emoji: "🚽",
    aura: 1660,
    rizz: 30,
    drip: 22,
    mce: 85,
    wl: 45,
  },
  {
    id: "npc",
    name: "That One NPC",
    handle: "@npc",
    cat: "Meme",
    emoji: "🧍",
    aura: 1580,
    rizz: 22,
    drip: 20,
    mce: 15,
    wl: 30,
  },
  {
    id: "intern",
    name: "The Intern",
    handle: "@intern",
    cat: "Meme",
    emoji: "🥤",
    aura: 1440,
    rizz: 55,
    drip: 50,
    mce: 60,
    wl: 74,
  },
  {
    id: "jimmy",
    name: "Jimmy (Your Roommate)",
    handle: "@jimmy",
    cat: "Meme",
    emoji: "🛋️",
    aura: 1210,
    rizz: 35,
    drip: 30,
    mce: 44,
    wl: 51,
  },
  {
    id: "algorithm",
    name: "The Algorithm",
    handle: "@algorithm",
    cat: "Meme",
    emoji: "🌀",
    aura: 2030,
    rizz: 55,
    drip: 60,
    mce: 70,
    wl: 88,
  },
  {
    id: "redditor",
    name: "Average Redditor",
    handle: "@redditor",
    cat: "Meme",
    emoji: "🤓",
    aura: 890,
    rizz: 18,
    drip: 15,
    mce: 12,
    wl: 25,
  },
];

export const RANK_TITLES = [
  { min: 4000, title: "Internet Royalty", next: null },
  { min: 2000, title: "Aura God", next: 4000 },
  { min: 1000, title: "Protagonist", next: 2000 },
  { min: 500, title: "Main Character", next: 1000 },
  { min: 250, title: "Supporting Cast", next: 500 },
  { min: 100, title: "Side Character", next: 250 },
  { min: 0, title: "NPC", next: 100 },
];

export const CENSUS = [
  {
    id: "overrated",
    q: "Most overrated celebrity?",
    options: ["Taylor Swift", "Drake", "MrBeast", "Your Ex"],
  },
  {
    id: "farmer",
    q: "Biggest aura farmer?",
    options: ["MrBeast", "Kai Cenat", "IShowSpeed", "The Group Chat"],
  },
  {
    id: "mvp",
    q: "Internet MVP of the week?",
    options: ["Kendrick Lamar", "CaseOh", "The Intern", "Sabrina Carpenter"],
  },
  {
    id: "break",
    q: "Most likely to break the internet?",
    options: ["IShowSpeed", "MrBeast", "GTA VI", "Jimmy (Your Roommate)"],
  },
  {
    id: "mogged",
    q: "Who got mogged hardest this year?",
    options: ["Drake", "Your Ex", "That One NPC", "xQc"],
  },
  {
    id: "best",
    q: "Best thing on the internet right now?",
    options: ["Meme battles", "Golden Upvotes", "This census", "Your aura"],
  },
  {
    id: "anime",
    q: "Strongest aura in anime?",
    options: ["Gojo Satoru", "Goku", "Luffy", "Naruto"],
  },
  {
    id: "goat",
    q: "GOAT of the internet?",
    options: ["MrBeast", "Kai Cenat", "Messi", "Taylor Swift"],
  },
];

export const MARKET = [
  {
    id: "auraboost",
    emoji: "⚡",
    name: "Aura Boost",
    price: 50,
    desc: "+100 Aura to YOU. Instantly. Straight onto the board.",
  },
  {
    id: "golden",
    emoji: "🏆",
    name: "Golden Upvote",
    price: 150,
    desc: "+250 Aura to any player of your choice. Glaze responsibly.",
  },
  {
    id: "refill",
    emoji: "🔋",
    name: "Vote Refill",
    price: 120,
    desc: "+10 votes for today. Democracy, but make it a microtransaction.",
  },
  {
    id: "memepack",
    emoji: "🎭",
    name: "Meme Pack",
    price: 200,
    desc: "Unlock a random meme sticker on your profile card. Aesthetic.",
  },
  {
    id: "clouthack",
    emoji: "🚀",
    name: "Clout Hack",
    price: 300,
    desc: "Instantly +25% of your current Aura. Inflation, but make it clout.",
  },
  {
    id: "flexframe",
    emoji: "✨",
    name: "Flex Frame",
    price: 500,
    desc: "Golden glow frame around your profile card. The ultimate flex.",
  },
];

export const AVATARS = [
  "😎",
  "🔥",
  "👑",
  "🦄",
  "🥷",
  "🤖",
  "🐐",
  "👽",
  "🧠",
  "🌶️",
  "🕶️",
  "🐉",
  "⚡",
  "🍕",
  "🧊",
  "🚀",
];
export const STICKERS = ["🍌", "🧃", "🎪", "🦆", "🥶", "🫡", "🍿", "🐸"];
export const BATTLE_CATS = [
  "Rizz",
  "Aura",
  "Drip",
  "Influence",
  "Main Character Energy",
  "Fanbase",
];

export const FEED_TEMPLATES = [
  "{a} just mogged {b} in Main Character Energy 💀",
  "{a} gained +{n} Aura 🔥",
  "{a} fanbase activated +{n} Clout 🫡",
  "{b} got cooked in the Daily Census 💀",
  "{a} dropped a {n} W/L ratio this week 🐐",
  "The Group Chat crowned {a} Internet MVP 👑",
  "{a} claimed Top {n} Aura Worldwide 😎",
  "{b} is now officially an NPC 🧍",
  "{a} bought a Golden Upvote for {b} 🏆",
  "{a} +{n} Rizz in the Aura Market 💸",
  "The Algorithm blessed {a} with +{n} aura 🌀",
  "{a} and {b} are cooking in the group chat 🔥",
  "{a} bought the #{n} spot on the Clout Board 💰",
  "{a} flexed a {n}x bag to be #1 on the board 👑",
  "{a} paid to stand above {b}. No votes. Just bag. 💸",
];

/* ------------------------- Cash Shop (real money, Stripe) ------------------------- */
// Prices in cents (USD). `slot` is the outbid.lol mechanic: rank is what you pay.
export const CASH_SHOP = {
  slot: {
    label: "Board Slot",
    minCents: 300, // $3 minimum bid
    tiers: [300, 500, 1000, 2500, 5000, 10000], // $3 / $5 / $10 / $25 / $50 / $100
    desc: "Claim a spot at the TOP of the Aura Leaderboard. Rank is what you pay — outbid everyone, become #1. Includes the ✓ Aura Verified badge.",
  },
  golden: {
    label: "Cash Golden Upvote",
    price: 200, // $2
    desc: "Drop real cash on a +500 Aura Golden Upvote for any celebrity. Public feed shoutout. Pure glaze, zero shame.",
  },
  frame: {
    label: "Permanent Flex Frame",
    price: 500, // $5
    desc: "Golden glow around your profile card. Forever. The ultimate paid flex.",
  },
};

/* ------------------------- achievements & badges ------------------------- */
// Tiers drive the badge color: bronze → silver → gold → platinum.
export const ACHIEVEMENT_TIERS = {
  bronze: "#cd7f32",
  silver: "#c0c0c0",
  gold: "#ffd76a",
  platinum: "#7ff3ff",
};

// `check` receives the user record (see api/state.mjs) and returns truthy when
// the badge is earned. Evaluation runs on every state-changing action.
export const ACHIEVEMENTS = [
  // voting
  {
    id: "first-vote",
    name: "First Ballot",
    emoji: "🗳️",
    tier: "bronze",
    desc: "Cast your first vote on the board.",
    check: (u) => u.votesCast >= 1,
  },
  {
    id: "voice-heard",
    name: "Voice Heard",
    emoji: "📢",
    tier: "silver",
    desc: "Cast 25 votes.",
    check: (u) => u.votesCast >= 25,
  },
  {
    id: "vote-enthusiast",
    name: "Vote Enthusiast",
    emoji: "🗳️",
    tier: "gold",
    desc: "Cast 50 votes.",
    check: (u) => u.votesCast >= 50,
  },
  {
    id: "electoral-college",
    name: "Electoral College",
    emoji: "🏛️",
    tier: "gold",
    desc: "Cast 100 votes.",
    check: (u) => u.votesCast >= 100,
  },
  {
    id: "ballot-stuffer",
    name: "Ballot Stuffer",
    emoji: "📦",
    tier: "platinum",
    desc: "Cast 200 votes. Democracy machine.",
    check: (u) => u.votesCast >= 200,
  },
  // aura ladder
  {
    id: "centurion",
    name: "Century",
    emoji: "💯",
    tier: "bronze",
    desc: "Reach 100 aura.",
    check: (u) => u.aura >= 100,
  },
  {
    id: "rising-star",
    name: "Rising Star",
    emoji: "🌟",
    tier: "bronze",
    desc: "Reach 250 aura.",
    check: (u) => u.aura >= 250,
  },
  {
    id: "influencer",
    name: "Influencer",
    emoji: "📈",
    tier: "silver",
    desc: "Reach 500 aura.",
    check: (u) => u.aura >= 500,
  },
  {
    id: "aura-millionaire",
    name: "Aura Millionaire",
    emoji: "💵",
    tier: "silver",
    desc: "Reach 1,000 aura.",
    check: (u) => u.aura >= 1000,
  },
  {
    id: "aura-god",
    name: "Aura God",
    emoji: "🕶️",
    tier: "gold",
    desc: "Reach 2,000 aura.",
    check: (u) => u.aura >= 2000,
  },
  {
    id: "mogul",
    name: "Mogul",
    emoji: "👑",
    tier: "gold",
    desc: "Reach 5,000 aura.",
    check: (u) => u.aura >= 5000,
  },
  {
    id: "legend",
    name: "Legend",
    emoji: "🏛️",
    tier: "platinum",
    desc: "Reach 10,000 aura.",
    check: (u) => u.aura >= 10000,
  },
  {
    id: "untouchable",
    name: "Untouchable",
    emoji: "☄️",
    tier: "platinum",
    desc: "Reach 20,000 aura. Beyond the board.",
    check: (u) => u.aura >= 20000,
  },
  // battles
  {
    id: "battle-winner",
    name: "Gladiator",
    emoji: "⚔️",
    tier: "silver",
    desc: "Win a battle.",
    check: (u) => u.battlesWon >= 1,
  },
  {
    id: "battle-champ",
    name: "Undisputed",
    emoji: "🥊",
    tier: "gold",
    desc: "Win 10 battles.",
    check: (u) => u.battlesWon >= 10,
  },
  {
    id: "battle-royale",
    name: "Battle Royale",
    emoji: "⚔️",
    tier: "platinum",
    desc: "Win 25 battles.",
    check: (u) => u.battlesWon >= 25,
  },
  // census
  {
    id: "census-voter",
    name: "Census Taker",
    emoji: "📊",
    tier: "bronze",
    desc: "Answer a census question.",
    check: (u) => u.censusVotes >= 1,
  },
  {
    id: "census-addict",
    name: "Census Addict",
    emoji: "📊",
    tier: "silver",
    desc: "Answer 10 census questions.",
    check: (u) => u.censusVotes >= 10,
  },
  {
    id: "pollster",
    name: "Pollster",
    emoji: "🗳️",
    tier: "gold",
    desc: "Answer 25 census questions.",
    check: (u) => u.censusVotes >= 25,
  },
  // cash / golden
  {
    id: "golden-gifter",
    name: "Sugar Daddy",
    emoji: "💸",
    tier: "gold",
    desc: "Drop a Golden Upvote.",
    check: (u) => u.goldenGifts >= 1,
  },
  {
    id: "glaze-lord",
    name: "Glaze Lord",
    emoji: "💸",
    tier: "platinum",
    desc: "Drop 3 Golden Upvotes.",
    check: (u) => u.goldenGifts >= 3,
  },
  // teams
  {
    id: "team-player",
    name: "Team Player",
    emoji: "🤝",
    tier: "silver",
    desc: "Join a team.",
    check: (u) => !!u.teamId,
  },
  {
    id: "founder",
    name: "Founder",
    emoji: "🚩",
    tier: "gold",
    desc: "Found a team.",
    check: (u) => u.teamsFounded >= 1,
  },
  {
    id: "squad-goals",
    name: "Squad Goals",
    emoji: "👥",
    tier: "silver",
    desc: "Be in a team of 5+.",
    check: (u) => u.teamSize >= 5,
  },
  // competitions
  {
    id: "competitor",
    name: "Competitor",
    emoji: "🏅",
    tier: "bronze",
    desc: "Enter a competition.",
    check: (u) => u.competitions >= 1,
  },
  {
    id: "comp-veteran",
    name: "Comp Veteran",
    emoji: "🏅",
    tier: "silver",
    desc: "Enter 3 competitions.",
    check: (u) => u.competitions >= 3,
  },
  {
    id: "triple-threat",
    name: "Triple Threat",
    emoji: "🎯",
    tier: "gold",
    desc: "Enter 5 competitions.",
    check: (u) => u.competitions >= 5,
  },
  {
    id: "champion",
    name: "Champion",
    emoji: "🏆",
    tier: "platinum",
    desc: "Win a competition.",
    check: (u) => u.wins >= 1,
  },
  {
    id: "back-to-back",
    name: "Back-to-Back",
    emoji: "🏆",
    tier: "gold",
    desc: "Win 2 competitions.",
    check: (u) => u.wins >= 2,
  },
  // seasons / prestige / longevity
  {
    id: "hall-of-famer",
    name: "Hall of Famer",
    emoji: "⭐",
    tier: "platinum",
    desc: "Finish a season in the top 10.",
    check: (u) => u.prestige >= 1,
  },
  {
    id: "three-peat",
    name: "Three-Peat",
    emoji: "⭐",
    tier: "gold",
    desc: "Finish top-10 in 3 seasons.",
    check: (u) => u.prestige >= 3,
  },
  {
    id: "dynasty",
    name: "Dynasty",
    emoji: "👑",
    tier: "platinum",
    desc: "Finish top-10 in 5 seasons.",
    check: (u) => u.prestige >= 5,
  },
  {
    id: "main-character",
    name: "Main Character",
    emoji: "🎬",
    tier: "gold",
    desc: "Reach the #1 spot on the player leaderboard.",
    check: (u) => u.hitNo1,
  },
  {
    id: "diamond-hands",
    name: "Diamond Hands",
    emoji: "💎",
    tier: "silver",
    desc: "Hold the platform's top aura for 7 days.",
    check: (u) => u.no1Days >= 7,
  },
  {
    id: "platinum-grip",
    name: "Platinum Grip",
    emoji: "💎",
    tier: "platinum",
    desc: "Hold the platform's top aura for 30 days.",
    check: (u) => u.no1Days >= 30,
  },
];

/* ------------------------- seasons ------------------------- */
export const SEASON_LENGTH_MS = 28 * 86400000; // 28 days per season
export const HALL_OF_FAME_SIZE = 20; // personalities snapshot per season
export const HALL_OF_FAME_PLAYERS = 10; // top players snapshot per season

/* ------------------------- teams & competitions ------------------------- */
export const COMPETITION_TYPES = [
  { id: "aura", label: "Aura Sprint", desc: "Gain the most aura during the window." },
  { id: "votes", label: "Vote Storm", desc: "Cast the most votes during the window." },
];
